import type { AnalyticsRow } from "./api.js";
import { aggregatePages, aggregateTrafficSources } from "./analytics.js";

function number(value: unknown): number {
  const parsed = typeof value === "number" ? value : Number(value ?? 0);
  return Number.isFinite(parsed) ? parsed : 0;
}

function escapeHtml(value: unknown): string {
  return String(value)
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;")
    .replace(/'/g, "&#39;");
}

function table(title: string, headings: string[], rows: unknown[][]): string {
  if (!rows.length) return "";
  return `<section><h2>${escapeHtml(title)}</h2><table><thead><tr>${headings.map((heading) => `<th>${escapeHtml(heading)}</th>`).join("")}</tr></thead><tbody>${rows.map((row) => `<tr>${row.map((cell) => `<td>${escapeHtml(cell)}</td>`).join("")}</tr>`).join("")}</tbody></table></section>`;
}

export function generateReportHtml(projectId: number | string, days: number, analytics: AnalyticsRow[], generatedAt = new Date()): string {
  const traffic = aggregateTrafficSources(analytics);
  const pages = aggregatePages(analytics);
  const visitors = analytics.reduce((sum, row) => sum + number(row.uniqueVisitors ?? row.visitors), 0);
  const pageviews = analytics.reduce((sum, row) => sum + number(row.pageviews), 0);
  const sessions = analytics.reduce((sum, row) => sum + number(row.sessions), 0);
  const end = generatedAt.toISOString().slice(0, 10);
  const startDate = new Date(generatedAt);
  startDate.setUTCDate(startDate.getUTCDate() - days + 1);
  const start = startDate.toISOString().slice(0, 10);

  return `<!doctype html>
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Clarvivo analytics report — ${escapeHtml(projectId)}</title><style>
*{box-sizing:border-box}body{max-width:900px;margin:0 auto;padding:40px;font:14px/1.45 system-ui,-apple-system,"Segoe UI",sans-serif;color:#172033}h1{font-size:28px;margin:0 0 4px}h2{font-size:17px;margin:30px 0 10px}.sub{color:#64748b;margin-bottom:26px}.metrics{display:grid;grid-template-columns:repeat(3,1fr);gap:12px}.metric{border:1px solid #dbe2ea;border-radius:9px;padding:14px}.label,th{font-size:11px;text-transform:uppercase;letter-spacing:.05em;color:#64748b}.value{font-size:24px;font-weight:700;margin-top:3px}table{width:100%;border-collapse:collapse}th,td{text-align:left;padding:8px 10px;border-bottom:1px solid #e7ebf0}th{font-weight:650}.foot{margin-top:36px;padding-top:12px;border-top:1px solid #dbe2ea;color:#64748b;font-size:11px}@media print{body{padding:16px}.metric{break-inside:avoid}section{break-inside:avoid}}
</style></head><body><h1>Clarvivo analytics report</h1><div class="sub">Project ${escapeHtml(projectId)} · ${start} to ${end} · ${days} days</div><div class="metrics"><div class="metric"><div class="label">Visitors</div><div class="value">${visitors.toLocaleString("en-US")}</div></div><div class="metric"><div class="label">Pageviews</div><div class="value">${pageviews.toLocaleString("en-US")}</div></div><div class="metric"><div class="label">Sessions</div><div class="value">${sessions.toLocaleString("en-US")}</div></div></div>
${table("Traffic channels", ["Channel", "Visitors", "Share"], traffic.channels.map((row) => [row.channel, row.visitors, row.sharePercent === undefined ? "—" : `${row.sharePercent}%`]))}
${table("Top pages", ["Page", "Views", "Unique visitors", "Bounce", "Avg time"], pages.map((row) => [row.path, row.views, row.uniqueVisitors, row.bouncePercent === undefined ? "—" : `${row.bouncePercent}%`, row.avgTimeSeconds === undefined ? "—" : `${row.avgTimeSeconds}s`]))}
${table("Top sources", ["Source", "Medium", "Campaign", "Visitors", "Conversions", "Revenue"], traffic.sources.map((row) => [row.source, row.medium, row.campaign, row.visitors, row.conversions ?? "—", row.revenue ?? "—"]))}
<div class="foot">Generated by Clarvivo. Open this file in a browser and use Print → Save as PDF.</div></body></html>`;
}
